##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################


elasticsearch:
  host_data_path: /data/demo-staging/elasticsearch

minio:
  host_data_path: /data/demo-staging/minio

mongodb:
  host_data_path: /data/demo-staging/mongodb

postgres:
  host_data_path: /data/demo-staging/postgres

influxdb:
  host_data_path: /data/demo-staging/influxdb

monitoring:
  enabled: false