##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################

elasticsearch:
  reindex_enabled: false

countryconfig:
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_DATABASE_URL
  env:
    OPENCRVS_ENVIRONMENT: prod
    OPENID_PROVIDER_CLAIMS: name,family_name,given_name,middle_name,birthdate,address
    OPENID_PROVIDER_CLIENT_ID: 8iM8fdsPG5aQy0rvYpOK95BeQ5mKM0UlsPMrTQGsqPs
    ESIGNET_REDIRECT_URL: https://esignet-mosipid.collab.mosip.net/authorize
    MOSIP_API_USERINFO_URL: https://mosip-api.farajaland-integration.opencrvs.dev/esignet/get-oidp-user-info
    VERIFIABLE_CREDENTIALS_SDJWT_ISSUE_URL: https://proxy.issuer.opencrvs.dev/openid4vc/sdjwt/issue
    VERIFIABLE_CREDENTIALS_RAW_JWT_SIGN_URL: https://proxy.issuer.opencrvs.dev/raw/jwt/sign
    NOTIFICATIONS_ENABLED: false

postgres_on_deploy:
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_POSTGRES_USER
      - REFERENCE_DATA_POSTGRES_PASSWORD
      - REFERENCE_DATA_EDITOR_USER
      - REFERENCE_DATA_EDITOR_PASSWORD
