---
- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_init_check

- name: Initialize Kubernetes cluster
  when: not kube_init_check.stat.exists
  shell: |
    sudo kubeadm init \
      --apiserver-advertise-address={{ kube_api_host | default(ansible_default_ipv4.address, true) }} \
      --pod-network-cidr={{ pod_network_cidr }} \
      --control-plane-endpoint={{ kube_api_host | default(ansible_default_ipv4.address, true) }}
  register: kubeadm_init_result

- name: Create .kube directory for provision user
  file:
    path: /home/provision/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to provision user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/provision/.kube/config
    owner: "{{ ansible_user }}"
    # FIXME: double check provision workflow
    group: application
    mode: '0600'
    remote_src: yes
    force: yes
# FIXME: As Ops I would like to have dedicated master node, all workloads should go to workers
#        Current setup will spread load across all nodes, including master
- name: Single node setup
  register: taint_result
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  environment:
    KUBECONFIG: /home/provision/.kube/config
  failed_when: 
      - taint_result.rc != 0
      - '"not found" not in taint_result.stderr'

- name: Get join command for worker nodes
  shell: sudo kubeadm token create --print-join-command
  register: join_command

- name: Remove existing join command file if it exists
  local_action:
    module: file
    path: ./join-command.sh
    state: absent

- name: Save join command to local file
  local_action:
    module: copy
    content: "{{ join_command.stdout }}"
    dest: ./join-command.sh
    force: yes

- name: Display initialization result
  when: not kube_init_check.stat.exists
  debug:
    msg: "{{ kubeadm_init_result.stdout_lines }}"