- name: Download actions-runner-controller
  shell: |
    curl -sSL --retry-all-errors --retry 5 \
      -o /tmp/actions-runner-controller-{{ arc_chart_version }}.tgz \
      https://github.com/actions/actions-runner-controller/releases/download/actions-runner-controller-{{ arc_chart_version }}/actions-runner-controller-{{ arc_chart_version }}.tgz

- name: Deploy actions-runner-controller via Helm
  kubernetes.core.helm:
    name: actions-runner-controller
    chart_ref: "/tmp/actions-runner-controller-{{ arc_chart_version }}.tgz"
    release_namespace: actions-runner-system
    create_namespace: true
    values:
      githubWebhookServer:
        enabled: false
      authSecret:
        create: true
        github_token: "{{ kube_runner_token }}"
      podAnnotations:
        opencrvs.org/lastdeploy-timestamp: "{{ ansible_date_time.epoch }}"

- name: Create ServiceAccount for opencrvs-runner
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: opencrvs-runner
        namespace: actions-runner-system

- name: Grant cluster-admin to CI runner serviceaccount
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: opencrvs-runner-admin
      subjects:
        - kind: ServiceAccount
          name: opencrvs-runner
          namespace: actions-runner-system
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io

- name: Deploy opencrvs-infra-runner
  retries: 10
  delay: 60
  vars:
    base_labels:
      - "self-hosted"
      - "k8s"
      - "{{ kube_cluster_env }}"
    extra_labels: "{{ kube_self_hosted_runner_additional_labels | default('') | split(',') | reject('equalto','') | list }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: RunnerDeployment
      metadata:
        name: opencrvs-infra-runner
        namespace: actions-runner-system
      spec:
        replicas: 1
        template:
          spec:
            serviceAccountName: opencrvs-runner
            repository: "{{ repository }}"
            image: ghcr.io/opencrvs/opencrvs-github-runner:latest
            labels: "{{ base_labels + extra_labels }}"
