- name: Create scripts directory for {{ ansible_user }}
  file:
    # FIXME: Should we use /opt/opencrvs instead?
    path: /opt/opencrvs/scripts
    state: directory
    owner: "{{ ansible_user }}"
    group: application
    mode: '0775'

- name: Create script for kubernetes user management
  copy:
    src: ./files/add-k8s-user.sh
    dest: "/opt/opencrvs/scripts/add-k8s-user.sh"
    owner: "{{ ansible_user }}"
    group: 'application'
    mode: '0755'


- name: Install k8s-help script
  copy:
    src: ./files/k8s-help.sh
    dest: "/opt/opencrvs/scripts/k8s-help.sh"
    owner: "{{ ansible_user }}"
    group: 'application'
    mode: '0755'

- name: Install k8s-help MOTD message
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0755'

- name: Generate k8s cluster configuration files
  environment:
    PUBLIC_API_SERVER_IP: "{{ kube_api_host | default(ansible_default_ipv4.address, true) }}"
    ASK_PASSWORD: no
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    env
    cd /root
    /opt/opencrvs/scripts/add-k8s-user.sh {{ item.name }}-{{ kube_cluster_env }}
  with_items: '{{ users }}'
  when: item.state == 'present'

- name: Add useful bash functions and aliases for k8s from template
  blockinfile:
    path: /home/{{ item.name }}/.bashrc
    create: yes
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED - Useful functions and aliases"
    block: "{{ lookup('template', 'bashrc_additions.j2') }}"
  become: yes
  with_items: '{{ users }}'
  when: item.state == 'present'

- name: Distribute k8s configuration files
  with_items: '{{ users }}'
  when: item.state == 'present'
  shell: |
    rm -rf /home/{{ item.name }}/.kube
    mv /root/user-kubeconfigs/{{ item.name }}-{{ kube_cluster_env }} /home/{{ item.name }}/.kube
    chown -R {{ item.name }}:{{ item.name }} /home/{{ item.name }}/.kube
