##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################

env:
  OPENCRVS_ENVIRONMENT: qa

countryconfig:
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_DATABASE_URL