##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################

env:
  OPENCRVS_ENVIRONMENT: "qa"

mongodb:
  databases:
    - prefix: USER_MGNT
      db: user-mgnt
      user: user-mgnt
    - prefix: HEARTH
      db: hearth-dev
      user: hearth
      roles: "[{ role: 'readWrite', db: 'hearth' }, { role: 'readWrite', db: 'performance' }, { role: 'readWrite', db: 'hearth-dev' }]"
    - prefix: CONFIG
      db: application-config
      user: config
    - prefix: PERFORMANCE
      db: performance
      user: performance
    - prefix: METRICS
      db: metrics
      user: metrics
    - prefix: OPENHIM
      db: openhim-dev
      user: openhim
      roles: "[{ role: 'readWrite', db: 'openhim' }, { role: 'readWrite', db: 'openhim-dev' }]"
    - prefix: WEBHOOKS
      db: webhooks
      user: webhooks
    - prefix: NOTIFICATION
      db: notification
      user: notification
    - prefix: EVENTS
      db: events
      user: events
      roles: "[{ role: 'readWrite', db: 'events' }, {role: 'read', db: 'user-mgnt'}]"
    - prefix: UPLOADER
      db: uploaded-records
      user: uploader

postgres_on_deploy:
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_POSTGRES_USER
      - REFERENCE_DATA_POSTGRES_PASSWORD
      - REFERENCE_DATA_EDITOR_USER
      - REFERENCE_DATA_EDITOR_PASSWORD
    spc-coding-db-secret:
      - SPC_POSTGRES_PASSWORD
      - SPC_POSTGRES_USER

countryconfig:
  env:
    COD_URL: https://countryconfig.pankaj-qa.opencrvs.dev/causes-of-death?terms=
    UPLOADER_APP_URL: "https://uploader.pankaj-qa.opencrvs.dev"
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_DATABASE_URL
    spc-coding-db-secret:
      - SPC_CODING_DATABASE_URL
