---
- name: Setup Kubernetes Cluster
  hosts: master, workers
  gather_facts: yes
  become: yes
  tags: k8s
  tasks:
    - include_tasks:
        file: tasks/k8s/application.yml
        apply:
          tags:
            - application
      tags:
        - application

    - include_tasks:
        file: tasks/k8s/data-partition.yml
        apply:
          tags:
            - data-partition
      tags:
        - data-partition
    - include_tasks:
        file: tasks/k8s/validate-data-partition.yml
        apply:
          tags:
            - data-partition
            - decrypt-on-boot
      tags:
        - data-partition
        - decrypt-on-boot
    - include_tasks:
        file: tasks/k8s/decrypt-on-boot.yml
        apply:
          tags:
            - decrypt-on-boot
      tags:
        - decrypt-on-boot

    - name: Include system preparation tasks
      include_tasks:
        file: tasks/k8s/system-preparation.yml
        apply:
          tags:
            - system-preparation
      tags:
        - system-preparation
    - name: Include containerd installation tasks
      include_tasks:
        file: tasks/k8s/install-containerd.yml
        apply:
          tags:
            - k8s
      tags:
        - k8s
    - name: Include Kubernetes installation tasks
      include_tasks:
        file: tasks/k8s/install-kubernetes.yml
        apply:
          tags:
            - k8s
      tags:
          - k8s
    - name: Include Kubernetes private IP configuration tasks
      include_tasks:
        file: tasks/k8s/configure-private-ip.yml
        apply:
          tags:
            - k8s
      tags:
          - k8s

- name: Temporary UFW configuration for Kubernetes installation
  hosts: master
  become: yes
  tags: k8s
  tasks:
    - name: "Setup UFW with allow by default"
      ufw:
        state: enabled
        default: allow
        direction: incoming

- name: Kubernetes Master
  hosts: master
  tags: k8s
  tasks:
    - name: Include master initialization
      include_tasks: tasks/k8s/init-master.yml
    - name: Include network plugin installation
      include_tasks: tasks/k8s/install-network-plugin.yml
    - name: Upgrade cluster
      include_tasks: tasks/k8s/upgrade-k8s-master.yml

- name: Kubernetes Worker Nodes
  hosts: workers
  tags:
    - join-workers
    - k8s
  tasks:
    - name: Include worker node join cluster
      include_tasks: tasks/k8s/join-workers.yml
      when: single_node == false
    - name: Upgrade cluster
      include_tasks: tasks/k8s/upgrade-k8s-workers.yml

- name: Configure k8s cluster components
  hosts: master
  tags: k8s
  tasks:
    - name: Labels nodes
      include_tasks: tasks/k8s/label-nodes.yml
    - name: Install metrics server on control plane
      include_tasks: tasks/k8s/metrics-server.yml
    - name: Install helm
      include_tasks: tasks/k8s/install-helm.yml
    - name: Install cert-manager
      include_tasks: tasks/k8s/cert-manager.yml
    - name: Install k8s self-hosted runner
      include_tasks: tasks/k8s/self-hosted-runner.yml

- name: Additional configuration
  become: yes
  hosts: master
  tags: k8s
  tasks:
    # FIXME: It should be started under provision user
    - name: Configure Extra SANs for Kube API server
      include_tasks:
        file: tasks/k8s/kube-api-add-extra-sans.yml
        apply:
          tags:
            - k8s
      tags:
        - k8s
    - name: Distribute kubeconfig into users directory
      include_tasks:
        file: tasks/k8s/user-kubeconfig.yml
        apply:
          tags:
            - users
            - k8s
      tags:
        - users
        - k8s
- name: Common Kubernetes post configuration tasks
  hosts: master, workers
  become: yes
  gather_facts: yes
  tasks:
    - name: Setup kubelet eviction policies
      include_tasks:
        file: tasks/k8s/eviction-policy.yml
        apply:
          tags:
            - k8s
      tags:
        - k8s
    - name: Configure UFW rules
      include_tasks:
        file: tasks/k8s/ufw.yml
        apply:
          tags:
            - k8s
      tags:
        - k8s
