elasticsearch-admin-user:
  type: Opaque
  data:
  # The Elasticsearch superuser password. You can also use this to login to Kibana with the username "elastic" 
  # and you have superuser Elastic privileges. Kibana URL: https://kibana.<your_domain>
  - ELASTICSEARCH_SUPERUSER_PASSWORD: ELASTIC_PASSWORD

mongodb-admin-user:
  type: Opaque
  data:
  # The MongoDB superuser admin username. A powerful account that has all rights to OpenCRVS data
  - MONGODB_ADMIN_USER
  # The MongoDB superuser admin password.
  - MONGODB_ADMIN_PASSWORD

minio-opencrvs-users:
  type: Opaque
  data:
  # A username for a Minio superuser admin to login to the Minio console to view supporting document attachments submitted during registrations. https://minio-console.<your_domain>
  - MINIO_ROOT_USER
  # A password for a Minio superuser admin
  - MINIO_ROOT_PASSWORD

postgres-admin-user:
  type: Opaque
  data:
  - POSTGRES_USER
  - POSTGRES_PASSWORD

kibana-users-secret:
  type: Opaque
  data:
  - KIBANA_USERNAME
  - KIBANA_PASSWORD

# Traefik static SSL certificate
# backward compatible with existing implementation,
# See: https://documentation.opencrvs.org/v1.8/setup/3.-installation/3.3-set-up-a-server-hosted-environment/3.3.5-setup-dns-a-records/4.3.2.3-static-tls-certificates
traefik-cert:
  type: tls
  namespace: traefik
  data:
    - SSL_CRT: tls.crt
    - SSL_KEY: tls.key

# If backup is configured then workflow will use GitHub secrets for current environment
# If restore is configured then workflow will fetch secrets from source environment (usually production)
backup-server-ssh-credentials:
  type: Opaque
  data:
    - BACKUP_SERVER_USER: user
    - BACKUP_HOST_PRIVATE_KEY: ssh_key
    - BACKUP_HOST: host

backup-encryption-secret:
  type: Opaque
  data:
  # This is the password that is used to encrypt all the backups that OpenCRVS creates from
  # a production server and that are stored on the backup server. Use this passphrase to decrypt the backups.
  - BACKUP_ENCRYPTION_PASSPHRASE: backup_encryption_key


# RESTORE_ENCRYPTION_PASSPHRASE is fetched from source environment (usually production)
# Check workflow: github-to-k8s-sync-env.yml
restore-encryption-secret:
  type: Opaque
  data:
  - RESTORE_ENCRYPTION_PASSPHRASE: backup_encryption_key


# SMTP configuration for ElastAlert email notifications
smtp-config:
  type: Opaque
  data:
  - SENDER_EMAIL_ADDRESS
  - SMTP_HOST
  - SMTP_PASSWORD
  - SMTP_PORT
  - SMTP_SECURE
  - SMTP_USERNAME
  - ALERT_EMAIL
